= Pivotal Big Data Roadshow  - Hands-on Technical Workshop

Lab content for the Pivotal Big Data Roadshow (http://pivotal.io/big-data/data-roadshow).

== Roadshow Agenda 

The usual flow is the following:

- 09:00 - 10:15: "The Journey to Becoming a Data-Driven Enterprise"
- 10:15 - 10:30: Coffee Break
- 10:30 - 12:00: Internet of Things Demo and Architecture Overview
- 12:00 - 1:00:  Lunch & Birds of a Feather Discussion
- 1:00  - 3:00:  Hands-On Technical Workshop

This repository contains the material for the Hands-on Technical Workshop sessions

== Contents

So far this consists of:

* this README
* link:labs/gemfire[GemFire Lab] 
* link:labs/phd-hawq[PHD and Hawq]
* link:labs/springxd[Data Streaming with Spring XD, GemFire and PHD]

== Environment

The labs are built for running on any environment with the right products installed.  
For making it simpler, we'll deliver them as VMs.
 
VMs are delivered with the products installed, and labs will be cloned from this Github repo (containing instructions and scripts)
