= VMware has ended active development of this project, this repository will no longer be updated.

Pivotal Big Data Roadshow  - Hands-on Technical Workshop

Lab content for the Pivotal Big Data Roadshow (http://pivotal.io/big-data/data-roadshow).

== Roadshow Agenda 

The usual flow is the following:

- 09:00 - 10:15: "The Journey to Becoming a Data-Driven Enterprise"
- 10:15 - 10:30: Coffee Break
- 10:30 - 12:00: Internet of Things Demo and Architecture Overview
- 12:00 - 1:00:  Lunch & Birds of a Feather Discussion
- 1:00  - 3:00:  Hands-On Technical Workshop

This repository contains the material for the Hands-on Technical Workshop sessions

== Contents

So far this consists of:

* this README
* link:labs/springxd[Data Streaming with Spring XD, GemFire and PHD]
* link:labs/gemfire[GemFire Overview Lab] 
* link:labs/phd-hawq[PHD and Hawq Overview Lab]

== Environment

The labs are built for running on any environment with the right products installed.  
In order to make it simpler, we've created the Amazon public AMI *ami-c42301ac* (gpadmin/bebold) . 


This AMI can be used to provision new instances that are ready to run those labs. Make sure you get 16Gb of memory for your AMI (recommended EC2 instance type: m3.xlarge) 
 
