== Spring XD overview lab

This lab will go through a general overview using Spring XD.

Requirements

- http://projects.spring.io/spring-xd/[Spring XD] v1.1.0 + installed 

* Come back to bosh and check the deployment is still there --> BOSH and Ops Manager are out of sync. 
. SSH to the VMs and see running processes. Check monit logs and rabbit logs. Try to understand what’s wrong

=== Creating a simple stream

- Init a new BOSH release:

+
[source,bash]
----
$ bosh init release postgres-release
----
. We'll add a *framework* component that will set a Java system property containing a timestamp that indicates when the application was staged. To do that, first create +java-buildpack/lib/java_buildpack/framework/staging_timestamp.rb+ and add the following contents:
+
[source,ruby]
----
require 'java_buildpack/framework'

module JavaBuildpack::Framework

  # Adds a system property containing a timestamp of when the application was staged.
  class StagingTimestamp < JavaBuildpack::Component::BaseComponent
    def initialize(context)
      super(context)
    end

    def detect
      'staging-timestamp'
    end

    def compile
    end

    def release
      @droplet.java_opts.add_system_property('staging.timestamp', "'#{Time.now}'")
    end
  end
end
----


----
$ cd postgres-release
$ tree  
----
- Define which Jobs you'll need for your release. Understand the archutecture work behind creating a release: http://docs.cloudfoundry.org/bosh/create-release.html[BOSH documentation]
- For each job, run from the main release directory "bosh generate job <job_name>". In this example we'll create a single job called "postgres-server"
----
$ bosh generate job postgres-server
----
- Check the directory tree again 

=== Transforming data

- Init a new BOSH release:
----
$ bosh init release postgres-release
----
- Check the structure created
----
$ cd postgres-release
$ tree  
----
- Define which Jobs you'll need for your release. Understand the archutecture work behind creating a release: http://docs.cloudfoundry.org/bosh/create-release.html[BOSH documentation]
- For each job, run from the main release directory "bosh generate job <job_name>". In this example we'll create a single job called "postgres-server"
----
$ bosh generate job postgres-server
----
- Check the directory tree again 

=== Sinking to Gemfire

- Init a new BOSH release:
----
$ bosh init release postgres-release
----
- Check the structure created
----
$ cd postgres-release


----
check process psql
  with pidfile /var/vcap/jobs/postgres-server/data/postmaster.pid
  start program "/var/vcap/jobs/postgres-server/bin/pgsql_ctl start" with timeout 600 seconds
  stop program "/var/vcap/jobs/postgres-server/bin/pgsql_ctl stop"
  group vcap
----




Troubleshoot any issues until you have your first custom bosh release deployment!! (there are some corrections to be done!) The troubleshooting part is very important!! That's how you learn!!

Hints: 

- The failing canary will be kept by bosh for troubleshooting purposes
- When testing, subsequent deployments should be done using __bosh deploy --recreate__ , otherwise new additional VMs will be created (canary won't be updated unless __--recreate__ is specified).
- Check logs and try to understand what's going on. You can try to run the commands yourself once logged into the VM to understand what's wrong.
- Dr Nick created a project called https://github.com/drnic/bosh-solo[BOSH-Solo] which helps testing BOSH releases. You might want to give it a try! (not mandatory)

Good luck!! Next challenge is adding a Service Broker capable of provisioning PostgreSQL instances to the release you just created :)

If you'd like to check the solution for this lab, clone this repo: https://github.com/Pivotal-Field-Engineering/postgres-bosh-release[postgres-bosh-release]
